### ISSUE TITLE
Add ActivationState type parameter to Client

### ISSUE THREAD

**Issue by cramertj** [wmedrano/rust-jack#12]
This will allow functions to be split up based on whether the client is active or inactive, and for `Drop` to know if it needs to deactivate.

**Comment by cramertj** [comment]
I wound up going a different way with this for #16 -- I made separate structs for `ActivatedClient` and `Client`. @wmedrano let me know what you think.

**Comment by wmedrano** [comment]
It's alright, it works. Was the motivation for this just for the drop?

**Comment by cramertj** [comment]
It prevents the double drop and makes double-activation impossible (which wouldn't make any sense). It'll also allow us to prevent the user from making modifications to the client while it's active.
