### ISSUE TITLE
how can I help?

### ISSUE THREAD

**Issue by dpzmick** [wmedrano/rust-jack#23]
I started this: https://github.com/dpzmick/rust-easyjack a while ago (because I eventually would like to get around to writing a synth) when it looked like this repo would just turn into some simple bindings on the jack api, but I really like what you have been doing here recently.

I'm pretty sure rust doesn't need 3 different incomplete and competing rust bindings: 
![image](https://cloud.githubusercontent.com/assets/536697/19795282/e9fea994-9c9f-11e6-9699-05e7d704de5e.png)

It looks like you two have done some things much better than I have, if you would like I can direct my efforts at this project instead of continuing to work on my own.

**Comment by cramertj** [comment]
We'd greatly appreciate your help! Sorry for the delayed response-- I'm in my last quarter of University right now and I've been busy with interviews and such. 

We're currently working on developing the API to support the standard Jack use cases (audio send/recv/routing) in purely safe Rust. There are a few issues open that you could look at, but if there's anywhere you see room for improvement, feel free to jump on it!

Let me know if there's anything I can do to help.

**Comment by dpzmick** [comment]
I'll take a look as soon as I can and see what I might want to suggest pulling over from what I've started, then see if there are any examples from the official rust example list that I can bring in.

Hopefully I can use this in my own projects I am (thinking about) working on!
