### ISSUE TITLE
Merging jack-sys

### ISSUE THREAD

**Issue by cramertj** [wmedrano/rust-jack#25]
@wmedrano and myself have been added as owners of the jack-sys crate. We should publish a new version that lives in this repo and has updated bindings (including the `fn` -> `unsafe fn` changes that are currently keeping this repo pinned against mine own fork of jack-sys.

**Comment by cramertj** [comment]
To clarify, jack-sys should remain its own crate, but the code should live in this repository.

**Comment by wmedrano** [comment]
Sounds good.

**Comment by wmedrano** [comment]
#27
