### ISSUE TITLE
RUST_TEST_THREADS=1

### ISSUE THREAD

**Issue by wmedrano** [wmedrano/rust-jack#31]
Test may hang if `RUST_TEST_THREADS` is greater than 1.

Solutions:
1. Configure cargo to always run tests with 1 thread always, tests will run slow.
2. Make JACK work with multiple threads.

**Comment by cramertj** [comment]
How would you feel about just putting locks around all of the tests that might conflict with one another? Not an ideal solution, but it seems better than just requiring that everyone set an env variable.

**Comment by wmedrano** [comment]
sgtm, removes uneeded "what?!" moment when someone tries to run tests.

Some client functionality, specifically open, activate, deactivate, and close, has built and sleeps and a single mutex for testing. Ideally, this means you don't have to worry about stability issues and can code like [normal](https://github.com/wmedrano/rust-jack/blob/master/src/test/test_client_cback.rs#L141).

Some tests in `test_client_cback` expect a clean environment, though they don't necessarily need it. For example, client_cback_calls_after_client_registered() checks that the register history has only "client_cback_cacr_other". Expectations like this could be changed to conditions like "contains" and "doesn't contain". Perhaps changing this will allow the tests to pass appropriately, while still keeping the suite stable (no freezes).

**Comment by wmedrano** [comment]
Also, #50 may help with the annoyance of starting a server. We can create a global one in the tests with `lazy_static!`.
