### ISSUE TITLE
a 32 bit problem?

### ISSUE THREAD

**Issue by errz99** [wmedrano/rust-jack#36]
I'm on ubuntu studio 32 bit and this error appears when doing a basic compilation. I don't see it in another 64 bit system... Is it 32 bit related?

`   Compiling jack v0.2.1
error[E0308]: mismatched types
   --> /home/bdaemon/.cargo/registry/src/github.com-1ecc6299db9ec823/jack-0.2.1/src/client.rs:195:90
    |
195 |             let ports = j::jack_get_ports(self.client_ptr(), pnp.as_ptr(), tnp.as_ptr(), flags);
    |                                                                                          ^^^^^ expected u32, found u64

error[E0308]: mismatched types
   --> /home/bdaemon/.cargo/registry/src/github.com-1ecc6299db9ec823/jack-0.2.1/src/client.rs:482:35
    |
482 |                                   port_flags,
    |                                   ^^^^^^^^^^ expected u32, found u64

error[E0308]: mismatched types
   --> /home/bdaemon/.cargo/registry/src/github.com-1ecc6299db9ec823/jack-0.2.1/src/client.rs:483:35
    |
483 |                                   buffer_size)
    |                                   ^^^^^^^^^^^ expected u32, found u64

error: aborting due to 3 previous errors

error: Could not compile `jack`.

`

**Comment by wmedrano** [comment]
Can you try out this branch?
#37

**Comment by errz99** [comment]
version 2.2 seems to have solved the problem. 
Thanks!
