### ISSUE TITLE
jack_port_by_id not implemented yet

### ISSUE THREAD

**Issue by rhetr** [wmedrano/rust-jack#44]
it hasn't been mentioned that this function hasn't been implemented yet. out of curiosity, what's wrong with the current code [here](https://github.com/wmedrano/rust-jack/blob/70ed05f59e26b6913936a95d0db8c1bcec227e26/src/client/client.rs#L182)? Is this related to https://github.com/wmedrano/rust-jack/issues/33?

**Comment by wmedrano** [comment]
I wrapped the function but didn't test it, so I left it out.

**Comment by wmedrano** [comment]
Now I have some testing for port_registration_callback which gives port ids, so I should be able to test it.

I'll try to add it back in this weekend.

**Comment by wmedrano** [comment]
closed by #46
