### ISSUE TITLE
how to access `Client` from `JackHandler` safely

### ISSUE THREAD

**Issue by rhetr** [wmedrano/rust-jack#54]
thanks for addressing https://github.com/wmedrano/rust-jack/issues/44 . I'm trying to use `port_by_id()` now from within a `JackHandler::port_registration()` to get the port name but I'm not sure how to access a `Client` from a `JackHandler`. what is a safe way to do this?

**Comment by wmedrano** [comment]
This functionality should be safe and I can implement this, as Jack implements thread safety on client calls.

I can expose a .client method in JackHandler that gives a &Client reference

**Comment by wmedrano** [comment]
Also, I didn't know people were using this O.o.

How bad has the change for JackHandler functions taking & instead of &mut been?

**Comment by wmedrano** [comment]
How do you feel about?

```fn thread_init(&self, c: &Client)```
```fn process(&self, c: &Client)```
...
```fn port_registration(&self, c: &Client)```

**Comment by rhetr** [comment]
I haven't needed &mut and can't think of a reason why it'd be needed so it's been fine for me so far. 

Is there a reason to expose `&Client` as a parameter rather than with a `.client` method? I'm a Rust novice so I'm unaware of any specific differences, but in practice it seems like it'd be cleaner to only fetch `&Client` when needed through a `.client` method.

**Comment by wmedrano** [comment]
I was thinking of adding a `.client` method, but I realized that I can't add the method to the JackHandler trait, since it only specifies behavior, and their would be no good way to pull the client ptr from the abyss. 

ActiveClient, or Client, it doesn't matter, you would just the immutable methods associated with the JackClient trait.

**Comment by wmedrano** [comment]
#55
